#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt', '1.10.0'
cookbook 'build-essential'
cookbook 'git'
cookbook 'gunicorn'
cookbook 'nginx'
cookbook 'ohai'
cookbook 'python'
cookbook 'screen'
cookbook 'vim'

cookbook 'nodejs',
    git: 'https://github.com/mdxp/nodejs-cookbook.git'

#cookbook 'nvm',
#    git: 'https://github.com/hipsnip-cookbooks/nvm.git'

